import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js';
import {EffectComposer} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/postprocessing/UnrealBloomPass.js';

const video=document.querySelector('#video'),canvas=document.querySelector('#fx'),stage=document.querySelector('#stage');
const start=document.querySelector('#start'),prompt=document.querySelector('#prompt'),msg=document.querySelector('#message');
const camStatus=document.querySelector('#camStatus'),trackStatus=document.querySelector('#trackStatus'),handsEl=document.querySelector('#hands');
const energyEl=document.querySelector('#energy'),energyBar=document.querySelector('#energyBar'),energyText=document.querySelector('#energyText'),stability=document.querySelector('#stability');
const gesture=document.querySelector('#gesture'),stageText=document.querySelector('#stageText'),mode=document.querySelector('#mode'),warning=document.querySelector('#warning');
const clock=document.querySelector('#clock');setInterval(()=>clock.textContent=new Date().toLocaleTimeString('en-GB'),500);

const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(stage.clientWidth,stage.clientHeight,false);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,stage.clientWidth/stage.clientHeight,.1,100);camera.position.z=6;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(stage.clientWidth,stage.clientHeight),1.25,.75,.25);composer.addPass(bloom);
const core=new THREE.Mesh(new THREE.SphereGeometry(.42,64,64),new THREE.MeshBasicMaterial({color:0x000000}));scene.add(core);
const disk=new THREE.Mesh(new THREE.RingGeometry(.5,1.12,256,32),new THREE.MeshBasicMaterial({color:0xff3150,transparent:true,opacity:.82,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false}));disk.rotation.x=.18;scene.add(disk);
const ring=new THREE.Mesh(new THREE.TorusGeometry(.63,.045,24,256),new THREE.MeshBasicMaterial({color:0x8befff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending}));scene.add(ring);
const count=11000,pos=new Float32Array(count*3),vel=new Float32Array(count*3),seed=new Float32Array(count);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=.5+Math.pow(Math.random(),.55)*2.8;pos[i*3]=Math.cos(a)*r;pos[i*3+1]=(Math.random()-.5)*.22*(1.2-r/3);pos[i*3+2]=Math.sin(a)*r;vel[i*3]=Math.sin(a)*.002;vel[i*3+1]=(Math.random()-.5)*.001;vel[i*3+2]=-Math.cos(a)*.002;seed[i]=Math.random()}
const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(pos,3));const pts=new THREE.Points(pg,new THREE.PointsMaterial({color:0xff5870,size:.018,sizeAttenuation:true,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(pts);
let finger=new THREE.Vector3(0,0,0),target=new THREE.Vector3(0,0,0),energy=0,over=0,active=false,particles=[];
function explode(){for(let i=0;i<Math.min(3500,count);i++){const j=i*3;const p=new THREE.Vector3(pos[j],pos[j+1],pos[j+2]).normalize();const power=1+Math.random()*5;vel[j]=p.x*power*.018;vel[j+1]=p.y*power*.018;vel[j+2]=p.z*power*.018}over=0;energy=0;warning.style.display='none';stageText.textContent='DISINTEGRATED';}
function render(t){requestAnimationFrame(render);const dt=.016;finger.lerp(target,.16);const visible=active;core.visible=ring.visible=disk.visible=pts.visible=visible;if(visible){core.position.copy(finger);ring.position.copy(finger);disk.position.copy(finger);pts.position.copy(finger);disk.rotation.z=t*.0008*(1+energy*5);ring.rotation.z=-t*.0012;const s=.75+energy*1.8;core.scale.setScalar(s);ring.scale.setScalar(s);disk.scale.setScalar(s);pts.rotation.z=t*.00015*(1+energy*6);}
for(let i=0;i<count;i++){const j=i*3;if(energy<.98){const x=pos[j],y=pos[j+1],z=pos[j+2],r=Math.hypot(x,z)+.0001;const pull=Math.min(.00035,energy*.0005/(r*.25+1));vel[j]-=x/r*pull;vel[j+2]-=z/r*pull;vel[j]+=z/r*.0012;vel[j+2]-=x/r*.0012;vel[j]*=.999;vel[j+1]*=.999;pos[j]+=vel[j];pos[j+1]+=vel[j+1];pos[j+2]+=vel[j+2];}else{pos[j]+=vel[j];pos[j+1]+=vel[j+1];pos[j+2]+=vel[j+2];vel[j]*=.992;vel[j+1]*=.992;vel[j+2]*=.992}}
pg.attributes.position.needsUpdate=true;composer.render();}
render(0);
window.addEventListener('resize',()=>{renderer.setSize(stage.clientWidth,stage.clientHeight,false);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();composer.setSize(stage.clientWidth,stage.clientHeight)});

async function enableCamera(){start.disabled=true;start.textContent='INITIALIZING…';msg.textContent='Requesting camera permission…';try{if(!window.isSecureContext)throw new Error('Use HTTPS or localhost.');const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},facingMode:{ideal:'user'}},audio:false});video.srcObject=stream;await video.play();camStatus.textContent='ACTIVE';camStatus.style.color='#57ef79';prompt.style.display='none';mode.textContent='ACTIVE';msg.textContent='Camera active';await handTracking();}catch(e){console.error(e);start.disabled=false;start.textContent='ENABLE CAMERA';msg.textContent=e.name==='NotAllowedError'?'Camera permission was blocked. Allow camera access and try again.':e.message;camStatus.textContent='ERROR';}}
async function handTracking(){try{const {HandLandmarker,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const files=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');let tracker;try{tracker=await HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.55,minHandPresenceConfidence:.5,minTrackingConfidence:.5});}catch(_){tracker=await HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numHands:2,minHandDetectionConfidence:.5,minHandPresenceConfidence:.5,minTrackingConfidence:.5});}trackStatus.textContent='ACTIVE';let last=-1;const loop=()=>{if(video.readyState>=2&&video.currentTime!==last){last=video.currentTime;const r=tracker.detectForVideo(video,performance.now());processHands(r.landmarks||[])}requestAnimationFrame(loop)};loop();}catch(e){trackStatus.textContent='FAILED';trackStatus.style.color='#ff3148';msg.textContent='Camera works, but hand tracking failed to load. Check network access.';}}
function processHands(list){handsEl.textContent=list.length;if(!list.length){active=false;gesture.textContent='NO HAND';stageText.textContent='DORMANT';return}const h=list[0],up=(a,b)=>h[a].y<h[b].y,dist=(a,b)=>Math.hypot(h[a].x-h[b].x,h[a].y-h[b].y);const point=up(8,6)&&!up(12,10)&&!up(16,14)&&!up(20,18),pinch=dist(4,8)<.065,open=up(8,6)&&up(12,10)&&up(16,14)&&up(20,18),fist=!up(8,6)&&!up(12,10)&&!up(16,14)&&!up(20,18),two=list.length>=2;const x=(1-h[8].x-.5)*5.5,y=(.5-h[8].y)*3.4;target.set(x,y,0);active=point||pinch||open;if(point){gesture.textContent='POINT // SINGULARITY';stageText.textContent='CHARGING';energy=Math.min(1,energy+.0035);if(energy>.82){over+=.0035;warning.style.display='block'}if(over>.7)explode()}else if(pinch){gesture.textContent='PINCH // GRAVITY';stageText.textContent='GRAVITY WELL';energy=Math.min(1,energy+.001)}else if(open){gesture.textContent='PALM // PLASMA';stageText.textContent='PLASMA CORE';energy=Math.max(.25,energy-.002)}else if(fist){gesture.textContent='FIST // COLLAPSE';stageText.textContent='COLLAPSE';energy=Math.max(0,energy-.03);active=false}else if(two){gesture.textContent='TWO HANDS // PORTAL';stageText.textContent='PORTAL'}else{gesture.textContent='TRACKING';stageText.textContent='READY'}const pct=Math.round(energy*100);energyEl.textContent=pct+'%';energyText.textContent=pct+'%';energyBar.style.width=pct+'%';stability.textContent=Math.max(0,Math.round(100-energy*75))+'%';}
start.addEventListener('click',enableCamera);
